### ISSUE TITLE
为什么使用"sleep 9999999d"作为cfs-driver的前台进程呢？

### ISSUE THREAD

**Issue by pangsq** [chubaofs/chubaofs-csi#27]
- csi-node-daemonset.yaml和csi-controller-deployment.yaml中cfs-driver容器command都在最后指定了"sleep 9999999d"，是出于什么考虑呢？
- 因为没有liveness的检查，driver进程挂了之后，Pod没法自动恢复。

**Comment by chengyu-l** [comment]
> * csi-node-daemonset.yaml和csi-controller-deployment.yaml中cfs-driver容器command都在最后指定了"sleep 9999999d"，是出于什么考虑呢？

是为了避免kubernetes因资源问题优先杀死cfs-driver进程，因为杀死该进程，会导致该Pod内部的fuse进程全部被杀，从而影响整个Node上所有的Volume使用。采用这种写法，当资源不足时，kubernetes可以杀死单个fuse进程，或阻止新的fuse进程被拉起。

> * 因为没有liveness的检查，driver进程挂了之后，Pod没法自动恢复。

cfs-driver进程占用资源很小，进程相对简单和稳定，所以没有进行liveness检查。不过增加liveness检查可能更保险

**Comment by pangsq** [comment]
> > * csi-node-daemonset.yaml和csi-controller-deployment.yaml中cfs-driver容器command都在最后指定了"sleep 9999999d"，是出于什么考虑呢？
> 
> 是为了避免kubernetes因资源问题优先杀死cfs-driver进程，因为杀死该进程，会导致该Pod内部的fuse进程全部被杀，从而影响整个Node上所有的Volume使用。采用这种写法，当资源不足时，kubernetes可以杀死单个fuse进程，或阻止新的fuse进程被拉起。
> 
> > * 因为没有liveness的检查，driver进程挂了之后，Pod没法自动恢复。
> 
> cfs-driver进程占用资源很小，进程相对简单和稳定，所以没有进行liveness检查。不过增加liveness检查可能更保险
> 
> @pangsq

"因资源问题优先杀死cfs-driver进程" 我理解是因为当前cfs-driver的Pod没有设置resources.limits导致Pod的Qos级别较低，因此当发生系统级的OOM时相对于其他进程更容易被杀掉？
driver进程死亡导致fuse进程被杀，关于这个我们的做法是1.让systemd起fuse进程 2.让dockerd起容器去执行fuse(设想中)
