### ISSUE TITLE
Why is kubeconfig needed, trying to use plugin inside nomad

### ISSUE THREAD

**Issue by netdata-be** [chubaofs/chubaofs-csi#37]
Hi there,

I'm trying to get the csi plugin to work with nomad: https://www.nomadproject.io/docs/job-specification/csi_plugin

It seems that this is not that easy, it seems the plugin want to fetch the kubeconfig.
Why is that needed, can it work without?

Currently I have create this entrypoint for the plugin to do "something" inside nomad:

```
mkdir -p /var/run/secrets/kubernetes.io/serviceaccount


echo -ne 'ALONGSTRING' > /var/run/secrets/kubernetes.io/serviceaccount/token

# just some dummy veriables
export KUBERNETES_SERVICE_HOST=1.2.3.4
export KUBERNETES_SERVICE_PORT=1234

/cfs/bin/cfs-csi-driver -v=5 --endpoint=unix:///csi/csi.sock --nodeid=3249d90 --drivername=csi.chubaofs.com
```

Now the driver starts:

```
I1112 15:44:00.506035       8 driver.go:39] driverName:csi.chubaofs.com, version:1.0.0, nodeID:3249d90
E1112 15:44:00.506144       8 config.go:428] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I1112 15:44:00.506422       8 driver.go:85] Enabling controller service capability: CREATE_DELETE_VOLUME
I1112 15:44:00.506429       8 driver.go:97] Enabling volume access mode: SINGLE_NODE_WRITER
I1112 15:44:00.506433       8 driver.go:97] Enabling volume access mode: SINGLE_NODE_READER_ONLY
I1112 15:44:00.506436       8 driver.go:97] Enabling volume access mode: MULTI_NODE_READER_ONLY
I1112 15:44:00.506439       8 driver.go:97] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
I1112 15:44:00.509129       8 server.go:108] Listening for connections on address: unix:///csi/csi.sock
I1112 15:44:00.528707       8 utils.go:79] GRPC request: /csi.v1.Identity/Probe body: {}
I1112 15:44:00.529121       8 utils.go:84] GRPC response: /csi.v1.Identity/Probe return: {}
I1112 15:44:00.531677       8 utils.go:79] GRPC request: /csi.v1.Identity/GetPluginInfo body: {}
I1112 15:44:00.531977       8 utils.go:84] GRPC response: /csi.v1.Identity/GetPluginInfo return: {"name":"csi.chubaofs.com","vendor_version":"1.0.0"}
I1112 15:44:00.532636       8 utils.go:79] GRPC request: /csi.v1.Identity/GetPluginCapabilities body: {}
I1112 15:44:00.533372       8 utils.go:84] GRPC response: /csi.v1.Identity/GetPluginCapabilities return: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
I1112 15:44:00.534113       8 utils.go:79] GRPC request: /csi.v1.Identity/Probe body: {}
I1112 15:44:00.534325       8 utils.go:84] GRPC response: /csi.v1.Identity/Probe return: {}
I1112 15:44:00.534676       8 utils.go:79] GRPC request: /csi.v1.Controller/ControllerGetCapabilities body: {}
I1112 15:44:00.534930       8 utils.go:84] GRPC response: /csi.v1.Controller/ControllerGetCapabilities return: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1112 15:44:00.535548       8 utils.go:79] GRPC request: /csi.v1.Identity/GetPluginCapabilities body: {}
I1112 15:44:00.535785       8 utils.go:84] GRPC response: /csi.v1.Identity/GetPluginCapabilities return: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
```

It seems that it's not working as expected, as you can see the plugin does not returns the supported `capabilities`

**Comment by chengyu-l** [comment]
Removing the kubeconfig configuration parameter in the yaml file it may work. It is not necessary if the connection with API Server of Kubernetes does work in the container of Pod.

**Comment by chengyu-l** [comment]
In the output message it has `capabilities`, which `capabilities` do you mean?

**Comment by chengyu-l** [comment]
> Hi there,
> 
> I'm trying to get the csi plugin to work with nomad: https://www.nomadproject.io/docs/job-specification/csi_plugin
> 
> It seems that this is not that easy, it seems the plugin want to fetch the kubeconfig.
> Why is that needed, can it work without?
> 
> Currently I have create this entrypoint for the plugin to do "something" inside nomad:
> 
> ```
> mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
> 
> 
> echo -ne 'ALONGSTRING' > /var/run/secrets/kubernetes.io/serviceaccount/token
> 
> # just some dummy veriables
> export KUBERNETES_SERVICE_HOST=1.2.3.4
> export KUBERNETES_SERVICE_PORT=1234
> 
> /cfs/bin/cfs-csi-driver -v=5 --endpoint=unix:///csi/csi.sock --nodeid=3249d90 --drivername=csi.chubaofs.com
> ```
> 
> Now the driver starts:
> 
> ```
> I1112 15:44:00.506035       8 driver.go:39] driverName:csi.chubaofs.com, version:1.0.0, nodeID:3249d90
> E1112 15:44:00.506144       8 config.go:428] Expected to load root CA config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
> I1112 15:44:00.506422       8 driver.go:85] Enabling controller service capability: CREATE_DELETE_VOLUME
> I1112 15:44:00.506429       8 driver.go:97] Enabling volume access mode: SINGLE_NODE_WRITER
> I1112 15:44:00.506433       8 driver.go:97] Enabling volume access mode: SINGLE_NODE_READER_ONLY
> I1112 15:44:00.506436       8 driver.go:97] Enabling volume access mode: MULTI_NODE_READER_ONLY
> I1112 15:44:00.506439       8 driver.go:97] Enabling volume access mode: MULTI_NODE_MULTI_WRITER
> I1112 15:44:00.509129       8 server.go:108] Listening for connections on address: unix:///csi/csi.sock
> I1112 15:44:00.528707       8 utils.go:79] GRPC request: /csi.v1.Identity/Probe body: {}
> I1112 15:44:00.529121       8 utils.go:84] GRPC response: /csi.v1.Identity/Probe return: {}
> I1112 15:44:00.531677       8 utils.go:79] GRPC request: /csi.v1.Identity/GetPluginInfo body: {}
> I1112 15:44:00.531977       8 utils.go:84] GRPC response: /csi.v1.Identity/GetPluginInfo return: {"name":"csi.chubaofs.com","vendor_version":"1.0.0"}
> I1112 15:44:00.532636       8 utils.go:79] GRPC request: /csi.v1.Identity/GetPluginCapabilities body: {}
> I1112 15:44:00.533372       8 utils.go:84] GRPC response: /csi.v1.Identity/GetPluginCapabilities return: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
> I1112 15:44:00.534113       8 utils.go:79] GRPC request: /csi.v1.Identity/Probe body: {}
> I1112 15:44:00.534325       8 utils.go:84] GRPC response: /csi.v1.Identity/Probe return: {}
> I1112 15:44:00.534676       8 utils.go:79] GRPC request: /csi.v1.Controller/ControllerGetCapabilities body: {}
> I1112 15:44:00.534930       8 utils.go:84] GRPC response: /csi.v1.Controller/ControllerGetCapabilities return: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
> I1112 15:44:00.535548       8 utils.go:79] GRPC request: /csi.v1.Identity/GetPluginCapabilities body: {}
> I1112 15:44:00.535785       8 utils.go:84] GRPC response: /csi.v1.Identity/GetPluginCapabilities return: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
> ```
> 
> It seems that it's not working as expected, as you can see the plugin does not returns the supported `capabilities`

**Comment by netdata-be** [comment]
> The master branch do not need the kubeconfig, and you can try it.

I tried the master branch ( by compiling it myself, it seems there is no master tag on the dockerhub ?) But I still need to set some env vars in orde to start, otherwise I get:

```
/cfs/bin/cfs-csi-driver -v=5 --endpoint=unix:///csi/csi.sock --nodeid=349edcas --drivername=csi.chubaofs.com
I1117 11:40:47.662946      23 driver.go:39] driverName:csi.chubaofs.com, version:1.0.0, nodeID:hell.inuits.top
E1117 11:40:47.662988      23 driver.go:42] init client-go Clientset fail. kubeconfig:, err:unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E1117 11:40:47.663000      23 chubaofs.go:71] chubaofs.NewDriver error:unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

So I just created dummy values.

> In the output message it has capabilities, which capabilities do you mean?

Not sure if this is how it should work, doen't the reply need to contain the different `capabilities` the plugin supports ( like SINGLE_NODE_READER_ONLY ) ?

The reason why I ask is because nomad is not sending volume requests to the csi driver, and I'm not sure why.
I only see `NodeGetCapabilities` and `ControllerGetCapabilities` request in the log.

**Comment by netdata-be** [comment]
Hi there, even on master I have to make sure there is some dummy data inside the variables, otherwise I get this error:

```
/cfs/bin/cfs-csi-driver -v=5 --endpoint=unix:///csi/csi.sock --nodeid=hell.inuits.top --drivername=csi.chubaofs.com
I1117 11:40:47.662946      23 driver.go:39] driverName:csi.chubaofs.com, version:1.0.0, nodeID:hell.inuits.top
E1117 11:40:47.662988      23 driver.go:42] init client-go Clientset fail. kubeconfig:, err:unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
E1117 11:40:47.663000      23 chubaofs.go:71] chubaofs.NewDriver error:unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
```

Regarding `capabilities` I thought it was not correctly, but I'm wrong.

Is there any intrest in also letting the plugin to work with nomad?
I'm having the following errors right now, and I'm not sure how to fix them:

```
I1117 13:10:58.274505       8 utils.go:84] GRPC response: /csi.v1.Node/NodeGetCapabilities return: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
I1117 13:11:00.911595       8 utils.go:79] GRPC request: /csi.v1.Node/NodeStageVolume body: {"staging_target_path":"/csi/staging/mysql1/rw-file-system-single-node-writer","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_id":"vol-0b756b75620d63af5"}
I1117 13:11:00.912565       8 nodeserver.go:87] NodeStageVolume already mount, stagingTargetPath:/csi/staging/mysql1/rw-file-system-single-node-writer cost:5.395µs
I1117 13:11:00.912571       8 utils.go:84] GRPC response: /csi.v1.Node/NodeStageVolume return: {}
I1117 13:11:00.913219       8 utils.go:79] GRPC request: /csi.v1.Node/NodePublishVolume body: {"staging_target_path":"/csi/staging/mysql1/rw-file-system-single-node-writer","target_path":"/csi/per-alloc/29ac0636-c83f-c137-7e32-87e4f09059df/mysql1/rw-file-system-single-node-writer","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":1}},"volume_id":"vol-0b756b75620d63af5"}
W1117 13:11:00.913783       8 mount_helper_common.go:33] Warning: Unmount skipped because path does not exist: /csi/per-alloc/29ac0636-c83f-c137-7e32-87e4f09059df/mysql1/rw-file-system-single-node-writer
I1117 13:11:00.914534       8 nodeserver.go:61] NodePublishVolume mount success, targetPath:/csi/per-alloc/29ac0636-c83f-c137-7e32-87e4f09059df/mysql1/rw-file-system-single-node-writer cost:759.132µs
```

I'm more then willing to provide you with access for example if there is any interest in also letting csi work inside nomad.

**Comment by chengyu-l** [comment]
`init client-go Clientset fail. kubeconfig:, err:unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined`
csi driver use `client-go`  to query some information about `pv`  from `Kubernetes API Server` . I am not sure if it can work in `nomad `

`NodePublishVolume mount success` It looks like the PVC have been mounted successful. The waring message can be ignored.

We don't know much about `nomad`, and we are very pleasure if you can contribute for us.
