### ISSUE TITLE
Support associating chubaofs volume with a specific PV

### ISSUE THREAD

**Issue by n0rad** [chubaofs/chubaofs-csi#43]
Today I was able only to create a `PVC` and have auto provisioning of the `PV` and the chubaofs associated `volume` with generated IDs as names.

In some pet set case, it's necessary to closer manager `PV` and / or chubao `volumes`. 

So the CSI driver should be able to :

- Create `volumes` from a defined `PV` name
- Associating a `PV` to an existing `volume` that was created on chubaofs

**Comment by GongWilliam** [comment]
I'll think about it.


Associating a PV to an existing volume that was created on chubaofs
---------------------------------------------------
this situation can be done manually.

**Comment by chengyu-l** [comment]
The [static pv](https://github.com/chubaofs/chubaofs-csi/blob/master/examples/pv-static.yaml) and [pvc](https://github.com/chubaofs/chubaofs-csi/blob/master/examples/pvc-static.yaml) template files provide associating a PV to an existing volume that was created on chubaofs.
