### ISSUE TITLE
Support volume snapshotting / restoring

### ISSUE THREAD

**Issue by n0rad** [chubaofs/chubaofs-csi#44]
Volume snapshotting / restoring is an important feature to get a production ready filesystem. Is there any plan to implement it ?

**Comment by GongWilliam** [comment]
well, volume snapshotting / restoring these features are depend on chubaofs. 
chubaofs is not support snapshot feature right now. if chubaofs implements snapshot/clone features, chubaofs-csi will keep up with it.
