### ISSUE TITLE
Move "owner" from StorageClass yaml to PVC yaml

### ISSUE THREAD

**Issue by shuoranliu** [chubaofs/chubaofs-csi#9]
StorageClass yaml should involves cluster-specific information of ChubaoFS, while PVC yaml focuses on volume-specific information of ChubaoFS.

So the "owner" field in current StorageClass should be moved to PVC.

**Comment by chengyu-l** [comment]
Kubernetes do not support to set the "owner" in PVC

**Comment by gsoec** [comment]
If "owner" can not be set in PVC, how does PVC support multi-tenancy?
The only way to support multi-tenancy through CSI is using static PV,  is that correct?
